task: detection
evaluator:
  type: CocoEvaluator
  iou_types: ['bbox', ]
num_classes: 22
remap_mscoco_category: False
train_dataloader:
  type: DataLoader
  dataset:
    type: CocoDetection
    img_folder: /kaggle/input/datasets/gurruvigneshyadav/trashcan-coco/instance_version/train/
    ann_file: /kaggle/working/instance_0/instances_train_0idx.json
    return_masks: False
    transforms:
      type: Compose
      ops: ~
  shuffle: True
  num_workers: 4
  drop_last: True
  collate_fn:
    type: BatchImageCollateFunction
val_dataloader:
  type: DataLoader
  dataset:
    type: CocoDetection
    img_folder: /kaggle/input/datasets/gurruvigneshyadav/trashcan-coco/instance_version/val/
    ann_file: /kaggle/working/instance_0/instances_val_0idx.json
    return_masks: False
    transforms:
      type: Compose
      ops: ~
  shuffle: False
  num_workers: 4
  drop_last: False
  collate_fn:
    type: BatchImageCollateFunction